# Generated by Django 3.0.5 on 2020-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rdata',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pword', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
